In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
b = np.array([[1,2,3] , [3,4,5]])
print(b)
print(b.shape)        # dimentions of array
print(type(b))

print(b[0][0])      # printing a00 . in this indexing starts with 0,0

[[1 2 3]
 [3 4 5]]
(2, 3)
<class 'numpy.ndarray'>
1


In [15]:
# some standard matrixes
print(np.zeros((3,3)))
print(np.ones((4,3)))



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
ran = np.random.random((4,5))
print(ran)


[[0.59544797 0.77312743 0.56552802 0.55544745 0.12673594]
 [0.80620928 0.65229622 0.47109437 0.52161421 0.88505096]
 [0.96624144 0.25315838 0.39438802 0.81608113 0.37591497]
 [0.43853275 0.93728145 0.4487891  0.43994746 0.38222682]]


In [25]:
# You can change elements of any row or column like this
ran[1:3,0:3] = 4
print(ran)

[[0.59544797 0.77312743 0.56552802 0.55544745 0.12673594]
 [4.         4.         4.         0.52161421 0.88505096]
 [4.         4.         4.         0.81608113 0.37591497]
 [0.43853275 0.93728145 0.4487891  0.43994746 0.38222682]]


#### Mathematical operations on array

In [34]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(arr1 + arr2)
print(np.add(arr1,arr2))
print(np.sqrt(arr1))


[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [35]:
# MUltipication

# element wise
print(arr1*arr2)
print(np.divide(arr1,arr2))
print(arr1/arr2)
#

[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [36]:
# array dot product
# real matrix multipication
p = np.array([[1,2] , [3,4]])
q = np.array([[5,6] , [7,8]])
print(np.dot(p,q))

[[19 22]
 [43 50]]


In [37]:
# scaler multipication
r = np.array([1,2,3,4])
s = np.array([[1],[2],[3],[4]])
print(np.dot(r,s))

[30]


In [38]:
print(np.sum(r))

10


In [39]:
print(np.sum(s))

10


In [41]:
## assinging values of array r to array t
t = np.array(r**2)
print(t)

[ 1  4  9 16]


In [42]:
# reshaping or arrys
print(t.reshape(4,1))        # t will convert to shape 4*1 from 1*4

[[ 1]
 [ 4]
 [ 9]
 [16]]


In [43]:
arr3 = np.array([[1,2,3] , [4,5,6] , [7,8,9] , [10,11,12]])
print(arr3.shape)

(4, 3)


In [45]:
# You can array according to their dimentions
print(arr3.reshape(6,2))
print("  ")
print(arr3.reshape(2,6))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
  
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


####  Random functions

In [54]:
## aranged way of numbers
arr4 = (np.arange(10))
print(arr4)

[0 1 2 3 4 5 6 7 8 9]


In [55]:
print(np.random.shuffle(arr4))

None


In [56]:
print(np.random.rand(4,6))

[[0.83416129 0.23551558 0.65078085 0.44781523 0.81785951 0.70316999]
 [0.7240323  0.70522879 0.58584412 0.19842959 0.73077574 0.15087228]
 [0.14538097 0.25868862 0.00990375 0.03996256 0.71674612 0.30306026]
 [0.36472079 0.1497546  0.23344715 0.37001238 0.76307634 0.05245451]]


In [61]:
print(np.random.randint(1,10,7))

[3 5 5 5 7 7 9]


In [4]:
list1 = [0 ,1, 2, 3 ,4 ,5, 6, 7, 8, 9] 
print(np.random.choice(list1))              # print random value from this list 

6


In [68]:
arr6 = np.arange(2) + 5
print(arr6)

[5 6]


### Numpy advanced functions

- min/max
- mean
- median 
- average 
- std 
- var

In [5]:
arr8 = np.random.rand(3,4)
print(arr8)

[[0.6208357  0.07426926 0.2279685  0.01632727]
 [0.88469975 0.2495509  0.78941986 0.93488929]
 [0.06641522 0.20795394 0.93723051 0.0767205 ]]


In [9]:
# Min function -> will print minimum value 
print(np.min(arr8))

print(np.min(arr8 , axis = 0))   # axis 0 -> go through columns
print(np.min(arr8 , axis = 1))   # axis 1 -> go through rows

0.016327274709710737
[0.06641522 0.07426926 0.2279685  0.01632727]
[0.01632727 0.2495509  0.06641522]


In [11]:
# print maximum value from array
print(np.max(arr8))       

0.9372305068345869


In [13]:
arr9 = np.array([1,2,3,4,5])
print(arr9)

[1 2 3 4 5]


In [18]:
print(np.mean(arr9))
print(np.median(arr9))

3.0
3.0


In [17]:
print(np.median(arr8))
print(np.mean(arr8))

0.23875970160207138
0.4238567254424049


In [20]:
print(np.average(arr9))
print(np.average(arr8))

3.0
0.4238567254424049


In [23]:
print(np.std(arr8))
print(np.std(arr9))

0.3607225041760086
1.4142135623730951


In [24]:
print(np.var(arr8))
print(np.var(arr9))

0.13012072501901054
2.0


### Tensors -> 3-d arrays

In [41]:
# This will create an array of 4 channels , 3 rows and 3 column in each channel

X = np.ones((4,3,2) , dtype = "int32")       # dtype -> for datatype declearation
print(X)


[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [47]:
arr15 = np.ones((5) , dtype = "int32")
print(arr15)

[1 1 1 1 1]


In [50]:
print(arr15+10)   # 10 will add to each element of arr15
print(arr15*10)
print(arr15/10)


[11 11 11 11 11]
[10 10 10 10 10]
[0.1 0.1 0.1 0.1 0.1]


In [53]:
arr16 =np.array([1,2,3,4,5]) 
print(arr16**4)

[  1  16  81 256 625]


In [62]:
# Matrix multipication

arr17 = np.array([[1,2] ,[3,4]])
arr18 = np.array([[4,1] ,[3,2]])
print(np.dot(arr17 , arr18))

[[10  5]
 [24 11]]



### linalg method -> for linear algebra releated calculations


- inv
- det

In [66]:
# determinant of array

print(np.linalg.det(arr17))
print(np.linalg.det(arr18))

-2.0000000000000004
4.999999999999999


In [74]:
# Printing inverce of matrix -> arr17
arr20 = (np.linalg.inv(arr17))
print(arr20)

# verifying multipication
print(np.dot(arr17,arr20))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [79]:
# Psudo inverse -> when matrix is not inversible 

arr21 = np.array([[6,8] , [3,4]])
arr22 = np.linalg.pinv(arr21)
print(arr22)
print(np.dot(arr21 , arr22))


[[0.048 0.024]
 [0.064 0.032]]
[[0.8 0.4]
 [0.4 0.2]]


#### Solving eqn's using numpy.linalg

In [80]:
# Solving equations using numpy
# eqns are : 2x+3y = 8 , 3x+y=5

a = np.array([[2,3] , [3,1]])
b = np.array([8,5])
np.linalg.solve(a,b)                # will give values of X , Y

array([1., 2.])